name: List Project Issues

on:
  schedule:
     - cron: '0 4 * * *' 
  workflow_dispatch:
     
env:
  ORGANIZATION: xpirit-training
  PROJECT_ID: 3
  FETCH_COUNT: 50
 
jobs:
  list-project-issues:
    name: List Project Issues
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v3
        - name: Get Token
          id: get_workflow_token
          uses: peter-murray/workflow-application-token-action@v2
          with:
            application_id: ${{ vars.GH_APP_ID }}
            application_private_key: ${{ secrets.GH_APP_KEY }}
            organization: ${{ env.ORGANIZATION }}
        - name: List Issues
          env:
            GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
          run: gh project item-list ${{ env.PROJECT_ID }} --limit ${{ env.FETCH_COUNT }} --owner ${{ env.ORGANIZATION }}
