name: List Project Issues

on: [ workflow_dispatch ]
 
jobs:
  list-project-issues:
    name: List Project Issues
    runs-on: ubuntu-latest
    steps:
        - name: Get Token
          id: get_workflow_token
          uses: peter-murray/workflow-application-token-action@v2
          with:
            application_id: ${{ vars.GH_APP_ID }}
            application_private_key: ${{ secrets.GH_APP_KEY }}
            organization: ${{ vars.ORGANIZATION }}
        - name: List Issues
          env:
            GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
          run: gh project item-list ${{ vars.PROJECT_ID }} --limit ${{ vars.FETCH_COUNT }} --owner ${{ vars.ORGANIZATION }}
