name: List Project Issues

on: [ workflow_dispatch ]
 
jobs:
  list-project-issues:
    name: List Project Issues
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Get Token
          id: get_workflow_token
          uses: actions/create-github-app-token@v1
          with:
            app-id: ${{ vars.GH_APP_ID }}
            private-key: ${{ secrets.GH_APP_KEY }}
        - name: List Issues
          run: gh issue list
          env:
            GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
        - name: Create Issues
          run: gh issue create -t "⚙️ From Workflow" -b "Created using GH Actions with GitHub App"
          env:
            GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
        - name: List Issues
          run: gh issue list
          env:
            GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
