name: List Project Issues

on: [ workflow_dispatch ]
 
jobs:
  list-project-issues:
    name: List Project Issues
    runs-on: ubuntu-latest
    steps:
        - name: Get Token
          id: get_workflow_token
          uses: actions/create-github-app-token@v1
          with:
            app-id: ${{ vars.GH_APP_ID }}
            private-key: ${{ secrets.GH_APP_KEY }}
            github-api-url: "https://github.acme-inc.com/api/v3"
        - name: List Issues
          run: gh project item-list ${{ vars.PROJECT_ID }} --limit ${{ vars.FETCH_COUNT }} --owner ${{ vars.ORGANIZATION }}
          env:
            GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
